Repository simonsobs/socs, pull requests merged in 2020-10, with the labels that each got.

#110 Lakeshore session.data
  agents/lakeshore240/LS240_agent.py
  agents/lakeshore372/LS372_agent.py
  docs/agents/lakeshore240.rst
  docs/agents/lakeshore372.rst
Labels: enhancement

#103 Create synacc agent
  agents/synacc/Dockerfile
  agents/synacc/requirements.txt
  agents/synacc/synacc.py
  docker-compose.yml
  docs/agents/synacc.rst
Labels: new agent

#114 Add new status log fields from beta software
  agents/bluefors/bluefors_log_tracker.py
Labels: bug
