Repository simonsobs/socs, pull requests merged in 2022-06, with the labels that each got.

#302 Magpie updates and white noise monitor
  agents/magpie/magpie_agent.py
  docs/agents/magpie.rst
Labels: enhancement

#307 Fix single test file run example
  tests/README.rst
Labels: documentation

#294 Postfat updates
  agents/acu/acu_agent.py
  agents/acu/scan_helpers.py
  docs/agents/acu_agent.rst
  docs/conf.py
Labels: enhancement

#310 Run pre-commit hooks on ACU files
  .flake8
  agents/acu/acu_agent.py
  agents/acu/scan_helpers.py
Labels: cleanup

#314 Fix Cryomech CPA Agent acq process auto start
  agents/cryomech_cpa/cryomech_cpa_agent.py
  tests/integration/test_cryomech_cpa_agent_integration.py
Labels: bug

#309 Smurf emulator tune support
  agents/smurf_file_emulator/smurf_file_emulator.py
  docs/agents/smurf_file_emulator.rst
  tests/agents/test_smurf_file_emulator.py
Labels: enhancement
