Repository simonsobs/socs, pull requests merged in 2022-04, with the labels that each got.

#270 Separate shared code from several PRs
  docs/api.rst
  docs/index.rst
  socs/agent/moxaSerial.py
  socs/agent/pmx.py
  tests/agent/test_moxaSerial.py
  tests/agent/test_pmx.py
Labels: enhancement, cleanup

#266 Wiregird PR Docstring Formatting
  agents/synacc/synacc.py
  agents/test_agent/Dockerfile
  agents/test_agent/test_agent.py
  agents/wiregrid_actuator/src/Actuator.py
  agents/wiregrid_actuator/src/DigitalIO.py
  agents/wiregrid_actuator/wiregrid_actuator.py
  agents/wiregrid_kikusui/kikusui_agent.py
  docker-compose.yml
  docs/agents/synacc.rst
  docs/agents/wiregrid_actuator.rst
  docs/agents/wiregrid_encoder.rst
  docs/agents/wiregrid_kikusui.rst
  docs/index.rst
Labels: documentation

#178 Magpie agent
  .gitignore
  agents/magpie/Dockerfile
  agents/magpie/magpie_agent.py
  docker-compose.yml
  docs/_static/images/lyrebird_cmaps.png
  docs/_static/images/lyrebird_grid.png
  docs/_static/images/lyrebird_wafer.png
  docs/agents/magpie.rst
  docs/index.rst
Labels: new agent

#278 Remove several old Agents
  agents/hwp_sim/hwp_simulator_agent.py
  agents/ocs_plugin_so.py
  agents/pysmurf_archiver/Dockerfile
  agents/pysmurf_archiver/pysmurf_archiver_agent.py
  agents/pysmurf_archiver/requirements.txt
  agents/pysmurf_controller/requirements.txt
  agents/pysmurf_monitor/requirements.txt
  agents/smurf/Smurf_Agent.py
  agents/smurf/ocs.cfg
  agents/smurf/stream_simulator.py
  agents/smurf_recorder/Dockerfile
  agents/smurf_recorder/smurf_recorder.py
  bin/rename_fields
  docker-compose.yml
  docs/agents/pysmurf-controller.rst
  docs/agents/pysmurf-monitor.rst
  docs/agents/pysmurf/index.rst
  docs/agents/pysmurf/pysmurf-archiver.rst
  docs/agents/smurf_recorder.rst
  docs/index.rst
  requirements.txt
  setup.py
  socs/agent/smurf_recorder.py
  socs/db/pysmurf_files_manager.py
  socs/util.py
  tests/agents/test_pysmurf_archiver.py
  tests/agents/test_smurf_recorder.py
Labels: cleanup

#279 Misc docs fixes
  CONTRIBUTING.rst
  docs/agents/lakeshore370.rst
  docs/agents/lakeshore425.rst
  docs/agents/suprsync.rst
  docs/api.rst
  docs/developer/snmp.rst
  docs/developer/testing.rst
  docs/index.rst
  docs/user/installation.rst
  docs/user/intro.rst
  docs/user/network.rst
  docs/user/new_agents.rst
  socs/agent/vantage_pro2/vantage_pro2.py
Labels: documentation, cleanup

#236 Acu commanded position None handling
  agents/acu/acu_agent.py
Labels: bug

#235 Scan helpers generator
  agents/acu/acu_agent.py
  agents/acu/scan_helpers.py
Labels: enhancement

#284 Scpi psu monitor update
  agents/scpi_psu/scpi_psu_agent.py
Labels: enhancement

#282 Magpie detector monitoring in grafana
  agents/magpie/magpie_agent.py
Labels: enhancement

#283 Smurf file emulator realistic g3
  agents/smurf_file_emulator/smurf_file_emulator.py
  agents/smurf_file_emulator/status_sample.yaml
  docs/agents/smurf_file_emulator.rst
  tests/agents/test_smurf_file_emulator.py
Labels: enhancement
