Repository simonsobs/socs, pull requests merged in 2022-01, with the labels that each got.

#221 Lakeshore425 agent. This is for one of the sensors in CHWP system.
  agents/lakeshore425/Dockerfile
  agents/lakeshore425/LS425_agent.py
  docker-compose.yml
  docs/agents/lakeshore425.rst
  docs/index.rst
  socs/Lakeshore/Lakeshore425.py
Labels: new agent

#216 Smurf file emulator
  agents/smurf_file_emulator/Dockerfile
  agents/smurf_file_emulator/smurf_file_emulator.py
  docker-compose.yml
  docs/agents/smurf_file_emulator.rst
  docs/index.rst
  tests/agents/test_smurf_file_emulator.py
Labels: new agent

#228 Device Emulator pytest Fixture
  docs/developer/testing.rst
  socs/testing/__init__.py
  socs/testing/device_emulator.py
Labels: enhancement

#229 Create Lakeshore425 Agent integration tests
  .github/workflows/develop.yml
  .github/workflows/official-docker-images.yml
  .github/workflows/pytest.yml
  Dockerfile
  socs/testing/device_emulator.py
  tests/default.yaml
  tests/integration/__init__.py
  tests/integration/test_ls425_agent_integration.py
  tests/integration/util.py
Labels: enhancement

#231 update LS372 sampling rate
  agents/lakeshore372/LS372_agent.py
  socs/Lakeshore/Lakeshore372.py
  tests/integration/test_ls372_agent_integration.py
Labels: enhancement

#237 Fix testing docs API autodoc
  socs/testing/device_emulator.py
Labels: bug
