Repository simonsobs/socs, pull requests merged in 2022-05, with the labels that each got.

#281 Implement hwp rotation agent review suggestions, remove need for telnet, add tests
  agents/hwp_rotation/Dockerfile
  agents/hwp_rotation/rotation_agent.py
  agents/hwp_rotation/src/.pid_port_busy
  agents/hwp_rotation/src/__init__.py
  agents/hwp_rotation/src/get_direction
  agents/hwp_rotation/src/get_freq
  agents/hwp_rotation/src/moxaSerial.py
  agents/hwp_rotation/src/pid_controller.py
  agents/hwp_rotation/src/pmx.py
  agents/hwp_rotation/src/set_pid
  agents/hwp_rotation/src/set_scale
  agents/hwp_rotation/src/tune_direction
  agents/hwp_rotation/src/tune_freq
  agents/hwp_rotation/src/tune_stop
  docker-compose.yml
  docs/agents/hwp_rotation_agent.rst
  docs/index.rst
  socs/agent/pmx.py
  socs/testing/device_emulator.py
  tests/agent/test_pmx.py
  tests/agents/hwp_rotation/test_pid_controller.py
  tests/default.yaml
  tests/integration/test_hwp_rotation_agent_integration.py
Labels: enhancement

#157 Created hwp rotation agent
  agents/hwp_rotation/Dockerfile
  agents/hwp_rotation/rotation_agent.py
  agents/hwp_rotation/src/__init__.py
  agents/hwp_rotation/src/pid_controller.py
  docker-compose.yml
  docs/agents/hwp_rotation_agent.rst
  docs/index.rst
  socs/agent/pmx.py
  socs/testing/device_emulator.py
  tests/agent/test_pmx.py
  tests/agents/hwp_rotation/test_pid_controller.py
  tests/default.yaml
  tests/integration/test_hwp_rotation_agent_integration.py
Labels: new agent

#276 Add functionality for LS372 Agent to Initialize Device/Channel Settings Using Config File
  agents/lakeshore372/LS372_agent.py
  docs/agents/lakeshore372.rst
Labels: enhancement

#280 Pysmurf controller tasks
  agents/pysmurf_controller/Dockerfile
  agents/pysmurf_controller/pysmurf_controller.py
  docs/agents/pysmurf-controller.rst
  docs/conf.py
  tests/agents/test_pysmurf_controller.py
Labels: enhancement

#296 Run end-of-line-fixer and trailing-whitespace pre-commit hooks on all files
  .flake8
  .pre-commit-config.yaml
  LICENSE.txt
  README.rst
  agents/acu/scan_helpers.py
  agents/cryomech_cpa/cryomech_cpa_agent.py
  agents/fts_aerotech_stage/fts_aerotech_agent.py
  agents/hwp_rotation/Dockerfile
  agents/labjack/Dockerfile
  agents/labjack/cal_curves/GA10K4D25_cal_curve.txt
  agents/lakeshore372/LS372_agent.py
  agents/lakeshore425/LS425_agent.py
  agents/magpie/magpie_agent.py
  agents/meinberg_m1000/mibs/MBG-SNMP-LTNG-MIB.py
  agents/meinberg_m1000/mibs/MBG-SNMP-ROOT-MIB.py
  agents/meinberg_m1000/mibs/SNMPv2-MIB.py
  agents/pysmurf_controller/pysmurf_controller.py
  agents/pysmurf_monitor/Dockerfile
  agents/smurf_crate_monitor/smurf_crate_monitor.py
  agents/smurf_file_emulator/smurf_file_emulator.py
  agents/suprsync/Dockerfile
  agents/synacc/requirements.txt
  agents/xy_stage/xy_latrt_agent.py
  docker-compose.yml
  docs/_static/theme_overrides.css
  docs/agents/acu_agent.rst
  docs/agents/chwp_encoder.rst
  docs/agents/cryomech_cpa.rst
  docs/agents/fts_agent.rst
  docs/agents/lakeshore240.rst
  docs/agents/lakeshore336.rst
  docs/agents/lakeshore372.rst
  docs/agents/lakeshore425.rst
  docs/agents/latrt_xy_stage.rst
  docs/agents/magpie.rst
  docs/agents/meinberg_m1000_agent.rst
  docs/agents/pfeiffer.rst
  docs/agents/pfeiffer_tc400.rst
  docs/agents/pysmurf-controller.rst
  docs/agents/scpi_psu.rst
  docs/agents/smurf_crate_monitor.rst
  docs/agents/suprsync.rst
  docs/agents/synacc.rst
  docs/agents/tektronix3021c.rst
  docs/agents/vantage_pro2.rst
  docs/conf.py
  docs/developer/snmp.rst
  docs/user/installation.rst
  docs/user/sequencer.rst
  docs/user/webserver.rst
  socs/Lakeshore/Lakeshore336.py
  socs/Lakeshore/Lakeshore370.py
  socs/Lakeshore/Lakeshore372.py
  socs/Lakeshore/Lakeshore425.py
  tests/hardware/ls240/conftest.py
  tests/hardware/ls240/test_ls240_agent.py
  tests/hardware/test_cryomech-cpa.py
  tests/hardware/test_ls372.py
Labels: cleanup

#297 Run autopep8 on all files
  .flake8
  .pre-commit-config.yaml
  agents/bluefors/bluefors_log_tracker.py
  agents/chwp/hwpbbb_agent.py
  agents/cryomech_cpa/cryomech_cpa_agent.py
  agents/fts_aerotech_stage/fts_aerotech_agent.py
  agents/hwp_rotation/src/pid_controller.py
  agents/labjack/labjack_agent.py
  agents/lakeshore240/LS240_agent.py
  agents/lakeshore336/LS336_agent.py
  agents/lakeshore370/LS370_agent.py
  agents/lakeshore372/LS372_agent.py
  agents/lakeshore425/LS425_agent.py
  agents/magpie/magpie_agent.py
  agents/meinberg_m1000/meinberg_m1000_agent.py
  agents/pfeiffer_tc400/pfeiffer_tc400_agent.py
  agents/pfeiffer_tc400/pfeiffer_tc400_driver.py
  agents/pfeiffer_tpg366/pfeiffer_tpg366_agent.py
  agents/pysmurf_controller/pysmurf_controller.py
  agents/pysmurf_monitor/pysmurf_monitor.py
  agents/scpi_psu/scpi_psu_agent.py
  agents/smurf_crate_monitor/smurf_crate_monitor.py
  agents/smurf_file_emulator/smurf_file_emulator.py
  agents/smurf_stream_simulator/smurf_stream_simulator.py
  agents/suprsync/suprsync.py
  agents/synacc/synacc.py
  agents/tektronix3021c/tektronix_agent.py
  agents/vantagePro2_agent/vantage_pro2_agent.py
  agents/xy_stage/xy_latrt_agent.py
  bin/rename_fields
  setup.py
  simulators/lakeshore240/ls240_simulator.py
  simulators/lakeshore372/ls372_simulator.py
  socs/Lakeshore/Lakeshore240.py
  socs/Lakeshore/Lakeshore336.py
  socs/Lakeshore/Lakeshore370.py
  socs/Lakeshore/Lakeshore372.py
  socs/Lakeshore/Lakeshore425.py
  socs/agent/moxaSerial.py
  socs/agent/pmx.py
  socs/agent/scpi_psu_driver.py
  socs/agent/vantage_pro2/vantage_pro2.py
  socs/db/suprsync.py
  socs/snmp.py
  socs/testing/device_emulator.py
  tests/agents/test_bluefors_agent.py
  tests/agents/test_ls372_agent.py
  tests/agents/test_smurf_file_emulator.py
  tests/agents/test_suprsync_agent.py
  tests/hardware/ls240/test_ls240_agent.py
  tests/hardware/test_ls372.py
  tests/integration/test_ls372_agent_integration.py
  tests/integration/test_ls425_agent_integration.py
Labels: cleanup

#299 Run flake8 on all files
  .flake8
  .pre-commit-config.yaml
  README.rst
  agents/bluefors/bluefors_log_tracker.py
  agents/chwp/hwpbbb_agent.py
  agents/cryomech_cpa/cryomech_cpa_agent.py
  agents/hwp_rotation/src/pid_controller.py
  agents/lakeshore336/LS336_agent.py
  agents/lakeshore370/LS370_agent.py
  agents/lakeshore372/LS372_agent.py
  agents/magpie/magpie_agent.py
  agents/meinberg_m1000/meinberg_m1000_agent.py
  agents/pfeiffer_tc400/pfeiffer_tc400_agent.py
  agents/pfeiffer_tpg366/pfeiffer_tpg366_agent.py
  agents/pysmurf_monitor/pysmurf_monitor.py
  agents/scpi_psu/scpi_psu_agent.py
  agents/smurf_stream_simulator/smurf_stream_simulator.py
  bin/rename_fields
  simulators/lakeshore372/ls372_simulator.py
  socs/Lakeshore/Lakeshore240.py
  socs/Lakeshore/Lakeshore336.py
  socs/Lakeshore/Lakeshore370.py
  socs/Lakeshore/Lakeshore372.py
  socs/agent/moxaSerial.py
  socs/agent/pmx.py
  socs/snmp.py
  socs/testing/device_emulator.py
  socs/util.py
  tests/agents/test_cryomech_cpa_agent.py
  tests/agents/test_fts_aerotech_agent.py
  tests/agents/test_hwpbbb_agent.py
  tests/agents/test_ls240_agent.py
  tests/agents/test_ls372_agent.py
  tests/agents/test_ls425_agent.py
  tests/agents/test_meinberg_m1000_agent.py
  tests/agents/test_pfeiffer_tpg366_agent.py
  tests/agents/test_pysmurf_monitor.py
  tests/agents/test_scpi_psu_agent.py
  tests/agents/test_smurf_crate_monitor.py
  tests/agents/test_smurf_file_emulator.py
  tests/agents/test_smurf_stream_simulator.py
  tests/agents/test_suprsync_agent.py
  tests/agents/test_synacc.py
  tests/agents/test_tektronix_agent.py
  tests/agents/test_vantage_pro2_agent.py
  tests/hardware/ls240/conftest.py
  tests/integration/test_ls425_agent_integration.py
  tests/integration/test_pfeiffer_tc400_agent_integration.py
  tests/test_snmp.py
  tests/test_util.py
Labels: cleanup

#272 Update FTS aerotech agent to work with multiple different FTSes
  agents/fts_aerotech_stage/fts_aerotech_agent.py
  docs/agents/fts_agent.rst
Labels: enhancement

#183 Develop wiregrid_actuator, wiregrid_kikusui / modify synacc to record synaccess switch on/off
  agents/synacc/Dockerfile
  agents/synacc/synacc.py
  agents/wiregrid_actuator/Dockerfile
  agents/wiregrid_actuator/limitswitch_config.py
  agents/wiregrid_actuator/src/Actuator.py
  agents/wiregrid_actuator/src/DigitalIO.py
  agents/wiregrid_actuator/src/__init__.py
  agents/wiregrid_actuator/stopper_config.py
  agents/wiregrid_actuator/wg-actuator-entrypoint.sh
  agents/wiregrid_actuator/wiregrid_actuator.py
  agents/wiregrid_kikusui/Dockerfile
  agents/wiregrid_kikusui/kikusui_agent.py
  agents/wiregrid_kikusui/src/__init__.py
  agents/wiregrid_kikusui/src/common.py
  docker-compose.yml
  docs/agents/synacc.rst
  docs/agents/wiregrid_actuator.rst
  docs/agents/wiregrid_kikusui.rst
  docs/conf.py
  docs/index.rst
  socs/agent/pmx.py
Labels: new agent
