Repository simonsobs/socs, pull requests merged in 2022-02, with the labels that each got.

#173 Add ability to read out custom registers from labjack agent
  agents/labjack/Dockerfile
  agents/labjack/labjack_agent.py
  docs/agents/labjack.rst
Labels: enhancement

#243 Fix flaky ls372 acq test
  tests/integration/test_ls372_agent_integration.py
Labels: bug

#240 Build and Deploy socs to PyPI
  .github/workflows/deploy.yml
  .github/workflows/develop.yml
  .github/workflows/pytest.yml
  Dockerfile
  README.rst
  agents/smurf_stream_simulator/smurf_stream_simulator.py
  pyproject.toml
  requirements.txt
  requirements/testing.txt
  setup.py
  socs/agent/smurf_recorder.py
  tests/agents/test_smurf_recorder.py
Labels: enhancement

#245 Expand base test coverage for agents
  .github/workflows/develop.yml
  .github/workflows/pytest.yml
  tests/.coveragerc
  tests/agents/test_cryomech_cpa_agent.py
  tests/agents/test_fts_aerotech_agent.py
  tests/agents/test_hwpbbb_agent.py
  tests/agents/test_ls240_agent.py
  tests/agents/test_ls425_agent.py
  tests/agents/test_meinberg_m1000_agent.py
  tests/agents/test_ocs_plugin_so.py
  tests/agents/test_pfeiffer_tpg366_agent.py
  tests/agents/test_pysmurf_archiver.py
  tests/agents/test_pysmurf_controller.py
  tests/agents/test_pysmurf_monitor.py
  tests/agents/test_scpi_psu_agent.py
  tests/agents/test_smurf_crate_monitor.py
  tests/agents/test_smurf_stream_simulator.py
  tests/agents/test_synacc.py
  tests/agents/test_tektronix_agent.py
  tests/agents/test_vantage_pro2_agent.py
  tests/integration/test_ls372_agent_integration.py
  tests/test_snmp.py
  tests/test_util.py
Labels: enhancement

#242 Create integration tests for the LS240 Agent
  socs/Lakeshore/Lakeshore240.py
  socs/testing/device_emulator.py
  tests/default.yaml
  tests/integration/test_ls240_agent_integration.py
Labels: enhancement

#248 Fix npy extension issue
  agents/pysmurf_monitor/pysmurf_monitor.py
Labels: bug

#255 Updates to Pfeiffer TC400 Agent
  agents/pfeiffer_tc400/Dockerfile
  agents/pfeiffer_tc400/pfeiffer_tc400_agent.py
  agents/pfeiffer_tc400/pfeiffer_tc400_driver.py
  agents/pfeiffer_tc400/pfeiffer_vacuum_protocol.py
  agents/pfeiffer_tc400/requirements.txt
  docs/conf.py
  requirements/testing.txt
  tests/default.yaml
  tests/integration/test_pfeiffer_tc400_agent_integration.py
Labels: bug, enhancement

#257 Fix CI Wheel Builds
  .github/workflows/develop.yml
  README.rst
  requirements/testing.txt
  setup.py
  socs/agent/vantage_pro2/__init__.py
Labels: bug

#149 Created pfeiffer turbo controller agent
  agents/pfeiffer_tc400/Dockerfile
  agents/pfeiffer_tc400/pfeiffer_tc400_agent.py
  agents/pfeiffer_tc400/pfeiffer_tc400_driver.py
  agents/pfeiffer_tc400/requirements.txt
  docker-compose.yml
  docs/agents/pfeiffer_tc400.rst
  docs/conf.py
  docs/index.rst
  requirements/testing.txt
  tests/default.yaml
  tests/integration/test_pfeiffer_tc400_agent_integration.py
Labels: new agent
