Repository simonsobs/socs, pull requests merged in 2023-08, with the labels that each got.

#457 Separate blocks for each input/output in UPS Agent
  socs/agents/ups/agent.py
Labels: bug, agent: ups

#499 Update set_boresight method signature override
  socs/agents/acu/agent.py
Labels: documentation

#467 Suprsync archive stats
  socs/agents/suprsync/agent.py
  socs/db/suprsync.py
  socs/db/suprsync_cli.py
  tests/agents/test_suprsync_agent.py
Labels: enhancement

#500 LS372 Agent: Add ability in config file to set channel resistance range
  docs/agents/lakeshore372.rst
  socs/agents/lakeshore372/agent.py
Labels: enhancement, agent: ls372

#427 Hwp supervisor
  docs/agents/hwp_supervisor_agent.rst
  docs/conf.py
  docs/index.rst
  socs/agents/hwp_encoder/agent.py
  socs/agents/hwp_pid/agent.py
  socs/agents/hwp_pmx/agent.py
  socs/agents/hwp_pmx/drivers/PMX_ethernet.py
  socs/agents/hwp_supervisor/__init__.py
  socs/agents/hwp_supervisor/agent.py
  socs/plugin.py
  tests/agents/test_hwp_supervisor_agent.py
  tests/integration/test_hwp_pmx_agent_integration.py
Labels: new agent

#496 Fix ibootbar agent acq crashing during reconnection
  socs/agents/ibootbar/agent.py
Labels: bug

#512 swap LSL/LSR/ST1 <--> LSL/LSR/ST2 for the bug fix at the site
  socs/agents/wiregrid_actuator/agent.py
  socs/agents/wiregrid_actuator/limitswitch_config.py
  socs/agents/wiregrid_actuator/stopper_config.py
Labels: bug
