Repository simonsobs/socs, pull requests merged in 2023-06, with the labels that each got.

#451 Find calibration curve location within package
  socs/agents/labjack/agent.py
Labels: bug

#424 adds pysmurf-controller tag params
  docker/pysmurf_controller/Dockerfile
  socs/agents/pysmurf_controller/agent.py
  tests/agents/test_pysmurf_controller_agent.py
Labels: enhancement

#446 Updates to ibootbar Agent
  socs/agents/ibootbar/agent.py
  tests/default.yaml
  tests/integration/test_ibootbar_agent_integration.py
Labels: enhancement

#447 ACU Exercisor mode
  docs/agents/acu_agent.rst
  socs/agents/acu/agent.py
  socs/agents/acu/exercisor.py
Labels: enhancement

#459 Adds user tag param to the smurf file emulator ops
  socs/agents/smurf_file_emulator/agent.py
  tests/agents/test_smurf_file_emulator.py
Labels: enhancement

#463 Add protection mode monitoring to pmx agent
  docs/agents/hwp_pmx.rst
  socs/agents/hwp_pmx/agent.py
  socs/agents/hwp_pmx/drivers/PMX_ethernet.py
  tests/integration/test_hwp_pmx_agent_integration.py
Labels: enhancement

#436 Generator Agent
  docs/agents/generator.rst
  docs/index.rst
  requirements.txt
  setup.py
  socs/agents/generator/__init__.py
  socs/agents/generator/agent.py
  socs/agents/generator/config.yaml
  socs/plugin.py
Labels: new agent

#456 Suprsync CLI
  bin/suprsync
  setup.py
  socs/db/suprsync_cli.py
  tests/agents/test_suprsync_agent.py
Labels: enhancement

#454 Suprsync timecode dir finalization
  bin/suprsync
  docs/agents/suprsync.rst
  setup.py
  socs/agents/suprsync/agent.py
  socs/db/suprsync.py
  socs/db/suprsync_cli.py
  tests/agents/test_suprsync_agent.py
Labels: enhancement

#390 Fix 372 upload cal curve timeout issue
  socs/Lakeshore/Lakeshore372.py
Labels: bug, enhancement
